### ISSUE TITLE
Jetpack mobile browser check broken - supercache_filename() fails to invoke cache actions on phase 1 cache

### ISSUE THREAD

**Issue by Sentynel** [Automattic/wp-super-cache#132] opened 2016-08-21 17:36 UTC
After the WP 4.6 update and associated Jetpack changes, Supercache is serving desktop cached files to mobile browsers. Some added debugging shows that wp_super_cache_jetpack_cookie_check() isn't being invoked at phase 1; this appears to be because when supercache_filename() checks function_exists("apply_filters"), this is true at phase 1 as well as phase 2. This pattern is repeated at other places in wp-cache-phase1.php, so it may have broken other things as well.

I've worked around this locally by just forcing do_cacheaction to be always called rather than apply_filters, but I'm not submitting that as a PR because I'm assuming there's a reason the filter version is intended for use in phase 2.

**Comment by kraftbj** [comment] 2016-08-21 18:07
To confirm, is this happening under Jetpack 4.2.2 (released on Friday)? In 4.2.1, the mobile theme would never engaged due to an old, old few lines of bad code in Jetpack that had previously always been skipped over.

**Comment by Sentynel** [comment] 2016-08-21 18:08
Yes, this is in 4.2.2. We had the no mobile theme at all issue with 4.2.1; this is unrelated.

**Comment by opradu** [comment] 2016-08-23 14:52
Hi,
from our tests the issue is in wp-super-cache/wp-cache-phase1.php

- http://screencast.com/t/eEWM9T5u

One possible fix would be to change:
`if ( function_exists( "apply_filters" ) ) {`
to
`if ( function_exists( "apply_filters" ) && has_filter( 'supercache_filename_str' )) {`

**Comment by jchuckmailen** [comment] 2016-09-14 15:43
@opradu That appears to be a viable solution. After extensive testing this appears to resolve our particular issue. We're not using JetPack, but a mobile specific theme. The issue is the same, mobile pages are no longer being served after updating to WordPress 4.6.x - JetPack is not involved.

Your solution makes perfect sense. If the supercache_filename_str filter doesn't exist then it needs to move onto the else statement.

@kraftbj I didn't see any pull requests with this in it. Would it be best to submit one or can you confirm this will be resolved in the next update? - thanks!

**Comment by nicugergely** [comment] 2016-09-15 13:50
Obviously, the tip suggested by @opradu must be done only to the supercache_filename function.

**Comment by jchuckmailen** [comment] 2016-09-15 14:28
@nicugergely correct. supercache_filename() is the only function that needs the change. I believe it's line 653.

**Comment by DrLightman** [comment] 2016-09-30 15:18
Thank you for the temporary fix, I was struggling with this misbehaviour myself. Hope it goes to official repository soon.

**Comment by raresiordache** [comment] 2016-12-12 08:00
@opradu ' s solution doesn't work in my case. I did the changes in wp-cache-phase1.php, but nothing happens. Also, I've tried to put on disable the plugin, but nothing.
I've WP 4.7. Any other suggestions?>

**Comment by alperen0107** [comment] 2017-02-06 13:21
@opradu your solution was working fine but after 1.4.9 update its not working anymore. pls update solution. thank u so much. best regards.

**Comment by donnchawp** [comment] 2017-02-06 14:27
Check out #185 for a fix. WordPress 4.6 started loading plugin.php before advanced-cache.php which meant that add_filter() and apply_filters() are now defined in wp-cache-phase1.php

The plugin still needs to use cache_action because not everyone upgrades. :(

**Closed** 2017-02-07 17:50 UTC
