### ISSUE TITLE
Setting debug mode to true in wp-config.php reveals warnings about constants in wp super cache

### ISSUE THREAD

**Issue by sparkalow** [Automattic/wp-super-cache#23] opened 2015-03-13 14:50 UTC
```
Notice: Constant WP_POST_REVISIONS already defined in /Path/to/site/wp-config.php on line 101
```

Reproduce by setting define('WP_DEBUG', true); in wp-config.php. Should probably already be on if you developing a plugin.  

Makes it annoying to develop a plugin while super cache is enabled.

**Comment by jom** [comment] 2017-10-26 09:48
I'm not able to reproduce. WPSC seems to check if defined before defining constants. The example provided is a constant not used in WPSC. Closing the issue for now, but if it is still reproducible, would you mind pasting in the complete debug log that shows what constants WPSC is defining?

**Closed by jom** 2017-10-26 09:48 UTC
