### ISSUE TITLE
error: Cannot redeclare gzip_accepted

### ISSUE THREAD

**Issue by ttohin** [Automattic/wp-super-cache#505] opened 2017-12-20 16:48 UTC
I updated WP 4.9.1 to and wp-super-cache to 1.5.9 and I started getting the error:

`Fatal error: Cannot redeclare gzip_accepted() (previously declared in /home/omwyogar/public_html/wp-content/plugins/wp-super-cache/wp-cache-phase1.php:62) in /home/omwyogar/public_html/om-w-yoga.cz/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 4`

**Comment by stodorovic** [comment] 2017-12-20 17:11
It looks as issue related to opcache. It seems that old php files are still cached - https://core.trac.wordpress.org/ticket/36455
Please ask your hosting for advice how to flush opcache or maybe you can try to install plugin WP OPcache.

**Comment by rene-hermenau** [comment] 2017-12-29 09:38
I think it's not related to opcache

@ttohin It looks like you created another WordPress website in the subfolder of your main WordPress, right? Did you use WP Staging?

@stodorovic I am the author of WP Staging and all our users who are using WP Staging together with WP Super Cache are complaining this issue  since a recent WP Super Cache update. It was working before so something must have been changed here.

WP Staging creates a staging site in a subfolder of the main website for testing plugin and theme updates first before updating them on the live site. To bypass this issue for the moment we need to exclude wp super cache from the cloning process but than we can not test wp super cache any longer which is not a good thing.

o fix the issue permanetely we just need to check if gzip_accepted has been declared already or better create a method which checks if a site is a staging site. Jetpack had the same issue in a previous version until they wrote the is_staging_site() method https://github.com/Automattic/jetpack/blob/9e16317e8fe3113668cc95e2e5e20fdb38ffa374/class.jetpack.php#L6042

**Comment by stodorovic** [comment] 2017-12-29 10:31
I was able to reproduce issue related to opcache, but it's possible that's also issue related to WP Staging.

I'm guessing that's related to #465. Contanst `WPCACHEHOME` (_wp-config.php_) probably points to main website, but wp-cache-phase2.php could be loaded from plugin directory (staging site).

I just created simple workaround #511. @rene-hermenau  Could you test it?

**Comment by rene-hermenau** [comment] 2017-12-29 11:25
@stodorovic Great Job! I can confirm that https://github.com/Automattic/wp-super-cache/pull/511 is working and resolving the issue

**Comment by ttohin** [comment] 2018-01-02 11:52
@rene-hermenau , Yes, I have another WP site, but I don't use WP Staging.

**Comment by rene-hermenau** [comment] 2018-01-09 17:56
@stodorovic Is there anything we can do to speed up the release of this fix for next wp super cache plugin? There are more and more reports for this error by people who are using wp super cache on staging sites.

**Closed** 2018-02-13 17:25 UTC

**Comment by nimboya** [comment] 2018-03-05 15:19
Thank you for this. Saved my day.

**Comment by paulschreiber** [comment] 2018-05-19 04:33
I had a similar problem. I fixed it by restarting `php7.1-fpm`

**Comment by donnchawp** [comment] 2018-05-19 08:19
The current version of the plugin has this fix in it.

**Comment by paulschreiber** [comment] 2018-05-19 13:48
@donnchawp I know. I updated to 1.6.1 and had to restart FPM to clear the opcache (object cache).
