### ISSUE TITLE
Remove utm_source from your urls

### ISSUE THREAD

**Issue by mahnunchik** [Automattic/wp-super-cache#735] opened 2020-04-07 15:07 UTC
Hi,

Are you joking? 

* https://odd.blog/2010/02/22/remove-unused-utmsource-urls/#comment-672813
* and post itself https://odd.blog/2010/02/22/remove-unused-utmsource-urls/

It is worst even solution I ever seen.

**Comment by mahnunchik** [comment] 2020-04-07 15:08
What about another `utm_*` params? `fbclick`, `yaclick`, `glick` etc...

**Comment by donnchawp** [comment] 2020-04-07 15:24
Why would I be joking?

You could also enable "Don't cache pages with GET parameters. (?x=y at the end of a url)" but of course you'll be in trouble if most of your traffic comes with those parameters.

Those other parameters may not have existed back when that post was written ten years ago.

**Comment by markfinst** [comment] 2021-04-07 06:02
This is a duplicate of https://github.com/Automattic/wp-super-cache/issues/712 and should be closed.

**Closed** 2021-07-08 13:45 UTC
